name: run taiko hive tests

on:
  push:
    branches: [taiko]
  repository_dispatch:
    types: [start]
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: start hive test
    runs-on: [self-hosted, linux]
    steps:
      - name: Start test
        run: |
          TRIGGER_REPO=${{ github.event.client_payload.repo }} TRIGGER_REF=${{ github.event.client_payload.ref }}
          cd /mnt/disks/data/go/src/github.com/taikoxyz/hive && git checkout taiko && git pull origin taiko && make test
