name: Run Taiko Tests

on:
  push:
    branches: [taiko]
  repository_dispatch:
    types: [start]
  workflow_dispatch:
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Start Taiko Test
    runs-on: [self-hosted, linux]
    defaults:
      run:
        shell: bash
        working-directory: /mnt/disks/data/go/src/github.com/taikoxyz/hive
    steps:
      - name: Generate Result DirName
        id: result
        run: |
          echo "RESULTS_DIR=$(mktemp -d log.XXXXXX)" >> $GITHUB_OUTPUT

      - name: Start test
        id: test
        continue-on-error: true
        timeout-minutes: 10
        env:
          REPO: ${{ github.event.client_payload.repo }}
          REF: ${{ github.event.client_payload.ref }}
          REF_NAME: ${{ github.event.client_payload.ref_name }}
          HEAD_REF: ${{ github.event.client_payload.head_ref }}
          RESULTS_DIR: ${{ steps.result.outputs.RESULTS_DIR }}
        run: |
          git checkout taiko
          git pull origin taiko
          make test-client

      - name: Analysis Test Result
        id: analysis
        run: |
          content=$(sh analysis_taiko_client_result.sh ${{ steps.result.outputs.RESULTS_DIR }})
          echo "PR_NUM=$(echo ${{ github.event.client_payload.ref }} | cut -d '/' -f 3)" >> $GITHUB_OUTPUT
          echo "RESULT=${content}"  >> $GITHUB_OUTPUT

      - name: Show Some Info
        run: |
          echo PR_NUM: ${{ steps.analysis.outputs.PR_NUM }}
          echo RESULT: ${{ steps.analysis.outputs.RESULT }}

      - name: Comment taiko-client PR
        if: (github.event.client_payload.repo == 'taikoxyz/taiko-client') && startsWith(github.event.client_payload.ref,'refs/pull')
        run: |
          pr_number=$(echo ${{ github.event.client_payload.ref }} | cut -d '/' -f 3)
          curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{secrets.HIVE_RESULT}}" \
          https://api.github.com/repos/taikoxyz/taiko-client/dispatches \
          -d '{"event_type":"comment","client_payload":{"pr_number":${{ steps.analysis.outputs.PR_NUM }}, "results":"${{ steps.analysis.outputs.RESULT }}" }}'
