name: Run Taiko Tests

on:
  push:
    branches: [taiko]
  repository_dispatch:
    types: [start]
  workflow_dispatch:
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Start Taiko Test
    runs-on: [self-hosted, linux]
    env:
      REPO: ${{ github.event.client_payload.repo }}
      REF: ${{ github.event.client_payload.ref }}
      REF_NAME: ${{ github.event.client_payload.ref_name }}
      HEAD_REF: ${{ github.event.client_payload.head_ref }}
    defaults:
      run:
        shell: bash
        working-directory: /mnt/disks/data/go/src/github.com/taikoxyz/hive
    steps:
      - name: Generate Result DirName
        id: result
        run: |
          echo "RESULTS_DIR=workspace/logs/$(date +%s)" >> $GITHUB_OUTPUT
          # echo "RESULTS_DIR=workspace/logs/1674035356" >> $GITHUB_OUTPUT

      - name: Create Result Dir
        run: mkdir -p ${{ steps.result.outputs.RESULTS_DIR }}

      - name: Start test
        env:
          RESULTS_DIR: ${{ steps.result.outputs.RESULTS_DIR }}
        run: |
          # git checkout taiko
          # git pull origin taiko
          make testrpc

      - name: Analysis Test Result
        id: analysis
        run: |
          echo "PASS=$(jq '.testCases | map_values(.summaryResult.pass) | with_entries(select(.value==false)) | length' ${{ steps.result.outputs.RESULTS_DIR }}/*.json)" >> $GITHUB_OUTPUT

      - name: Comment taiko-client PR
        # if: ${{ startWith(github.event.client_payload.ref,"refs/pull") }}
        run: |
          echo ${{ steps.analysis.outputs.PASS }}
          # curl -X POST \
          # -H "Accept: application/vnd.github.everest-preview+json" \
          # -H "Authorization: Bearer ${{secrets.HIVE_RESULT}}" \
          # https://api.github.com/repos/taikoxyz/taiko-client/dispatches \
          # -d '{"event_type":"comment","client_payload":{"results":"pass:false, url:http://hive.a1.taiko.xyz/"}}'
